version: "3.7"
services:
  api_service:
    build:
      dockerfile: src/main/resources/Dockerfile
    container_name: spring_boot_container
    restart: always
    ports:
      - 8080:8080
    networks:
      - springapimysql-net
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/db_socialmedia?allowPublicKeyRetrieval=true
    depends_on:
      - mysqldb

  mysqldb:
    image: "mysql:8.0"
    container_name: mysql_container
    restart: always
    ports:
      - 3306:3306
    networks:
      - springapimysql-net
    environment:
      MYSQL_DATABASE: ${DB_LOCAL_NAME}
      MYSQL_PASSWORD: ${DB_LOCAL_PASS}
      MYSQL_ROOT_PASSWORD: ${DB_LOCAL_ROOT_PASS}
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - ./dbdata:/var/lib/mysql
networks:
  springapimysql-net:
    driver: bridge
